// packages/samples/vue/src/App.vue
<script setup lang="ts">
import { KolButton, KolInputDate } from '@public-ui/vue';

const date = defineModel('date');
date.value = new Date();

const handleDateInput = (event) => {
	date.value = event.target._value;
};

const increaseDate = () => {
	date.value = new Date(date.value.getTime() + 1000 * 60 * 60 * 24);
};
</script>

<template>
	<main>
		<KolInputDate _label="Date Input" :_value="date" @input="handleDateInput" />
		<KolButton _label="increase" :_on="{ onClick: increaseDate }" />
		<pre>
value: {{ JSON.stringify(date) }} ({{ typeof date }})
			</pre
		>
	</main>
</template>

<style>
html {
	font-family: sans-serif;
}
</style>

// packages/samples/angular/src/app/app.component.ts
import { Component, forwardRef } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { KoliBriModule, KolInputDate } from '@public-ui/angular-v18';
import { FormsModule, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
	selector: 'app-root',
	standalone: true,
	templateUrl: './app.component.html',
	imports: [RouterOutlet, KoliBriModule, FormsModule],
})
export class AppComponent {
	date = new Date();

	get dateJson() {
		return JSON.stringify(this.date);
	}

	get dateType() {
		return typeof this.date;
	}

	public handleInput(evt: Event) {
		const value = (evt.target as HTMLKolInputDateElement)._value;
		if (value instanceof Date) {
			this.date = value;
		}
	}

	public readonly increaseDate = () => {
		this.date = new Date(this.date.getTime() + 1000 * 60 * 60 * 24);
	};
}

<kol-input-date _label="Date Input" _value="{date}" [_value]="date" (input)="handleInput($event)" />
<kol-button _label="increase" (click)="increaseDate()" />
<pre>
value: {{ dateJson }} ({{ dateType }})
</pre>
