// packages/create-kolibri/templates/angular-app/src/angular.main.ts
// Polyfills
import 'core-js/features/reflect';
import 'zone.js/dist/zone';

import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './angular.module';

const ENVs = {
	NODE_ENV: '$$NODE_ENV$$',
};
if (ENVs.NODE_ENV === 'production') {
	enableProdMode();
}

const htmlDivElement: HTMLElement | null = document.querySelector<HTMLDivElement>('div#app');
if (htmlDivElement instanceof HTMLElement) {
	htmlDivElement.appendChild(document.createElement('app'));

	platformBrowserDynamic()
		.bootstrapModule(AppModule)
		.then(() => {})
		.catch(() => {})
		.finally(() => {});
}

// packages/create-kolibri/templates/preact-app/src/preact.main.tsx
import { render } from 'preact';
import React from 'react';

import { AppComponent } from './components/app/component';

import { register } from '@public-ui/core';
import { defineCustomElements } from '@public-ui/components/dist/loader';
import { ITZBund } from '@public-ui/themes';

register(ITZBund, defineCustomElements)
	.then(() => {
		const htmlElement: HTMLElement | null = document.querySelector<HTMLDivElement>('div#app');
		if (htmlElement instanceof HTMLElement) {
			render(<AppComponent />, htmlElement);
		}
	})
	.catch(console.warn);
